"""empty message

Revision ID: 691c320eefc8
Revises: 3a7a4f0ba7f8
Create Date: 2022-03-29 13:14:56.013107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691c320eefc8'
down_revision = '3a7a4f0ba7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'is_admin')
    # ### end Alembic commands ###
