"""empty message

Revision ID: 6f8581a44509
Revises: 
Create Date: 2022-02-16 18:03:52.267920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8581a44509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('dni', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('apellidos', sa.String(length=50), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
