"""empty message

Revision ID: c68d63f1dc80
Revises: 6f8581a44509
Create Date: 2022-02-17 17:02:23.757934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68d63f1dc80'
down_revision = '6f8581a44509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'nombre',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('cliente', 'apellidos',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cliente', 'imagen',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'imagen',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cliente', 'apellidos',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cliente', 'nombre',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
